### ISSUE TITLE
Publish documentation on adding a custom DNS server to the network

### ISSUE THREAD

**Issue by jheretic** [opentechinstitute/commotion-docs#315]
On a network without an internet connection, it is sometimes desirable to provide certain static domains for services connected to the network. One possible way to do that is by setting up a standalone local DNS server and configuring the nodes to use it. We should write up a documentation guide

**Comment by andygunn** [comment]
@dismantl - I believe you are working on this? To put it in Guides and How-tos?

**Comment by andygunn** [comment]
@dismantl -- closing this as the documentation has been merged to staging. Thanks!
