### ISSUE TITLE
Image URLs from oti.newamerica.net are broken on Somaliland post

### ISSUE THREAD

**Issue by jheretic** [opentechinstitute/commotion-docs#335]
Due to changes to the New America web presence, links to images on oti.newamerica.net no longer work correctly. This includes images on https://commotionwireless.net/blog/2013/12/12/building-mesh-network-rural-somaliland/ and possible elsewhere on the site. Those links should be corrected to local image URLs.

**Comment by andygunn** [comment]
Fixed, closing.
